In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.


In [3]:
"""In Python, the list and numpy.ndarray (often referred to as array when using NumPy) are two different data structures that 
serve different purposes. The list is a built-in Python data type for holding a collection of items, while numpy.ndarray is
a data structure provided by the NumPy library for efficient array computations."""
import numpy as np

# Create a Python list
list_ = [1, 2, 3, 4, 5]

# Create a NumPy array from the list
array_list = np.array(list_)

# Print the data types of both variables
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [6]:
# For variable_list
for i in list_:
    print(type(i))
# for array-list    
for j in array_list:
    print((type(i)))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [18]:
"""Yes, there will be a difference in the data types of the elements present in the variables list_ and array_list. When you create the NumPy array array_list with the dtype parameter set to int, the elements of the array will be 
explicitly converted to integers."""

'Yes, there will be a difference in the data types of the elements present in the variables list_ and array_list. When you create the NumPy array array_list with the dtype parameter set to int, the elements of the array will be \nexplicitly converted to integers.'

In [19]:
import numpy as np

# Original list
list_ = [1, 2, 3, 4, 5, 6]

# Creating a NumPy array from the list with dtype=int
array_list = np.array(list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [12]:
#Answer
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
arr_shape=np.shape(num_array)
arr_size=np.size(num_array)

In [13]:

print(arr_shape)
print(arr_size)

(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [14]:
#Answer
import numpy as np

# Create a 3x3 array of zeros
zero_matrix = np.zeros((3, 3))

print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [16]:
import numpy as np
ident_matrix=np.eye(5)

In [17]:
ident_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])